version = 0.1


[dev.deploy.parameters]
stack_name = "test-stack-backend"
s3_bucket = "test-stack-backend"
s3_prefix = "dev-artifacts"
region = "ap-south-1"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
disable_rollback = true