AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  description

Parameters:
    
  Environment:
    Type: String
    Description: Environment name
    AllowedValues:
      - dev
      - prod
    Default: dev
  
Globals:
  Api:      
    Cors:
      AllowMethods: "'GET,POST,OPTIONS'"
      AllowHeaders: "'*'"
      AllowOrigin: "'*'"
      AllowCredentials: "'*'"

  Function:
    Timeout: 12
    MemorySize: 256
    Runtime: nodejs18.x
    Handler: index.lambdaHandler
    Architectures:
      - x86_64

    Environment:
      Variables:
        ENVIRONMENT: !Ref Environment

    Layers:
      - !Ref commonLayer

Resources:

# roles ==================================================================================================================================
  lambdaExecutionRole:
    Type: AWS::IAM::Role
    Properties:
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/service-role/AWSLambdaRole
        - arn:aws:iam::aws:policy/AWSLambdaExecute
        - arn:aws:iam::aws:policy/AmazonSQSFullAccess
        - arn:aws:iam::aws:policy/AmazonSNSFullAccess
        - arn:aws:iam::aws:policy/AmazonSESFullAccess
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Principal:
              Service:
                - lambda.amazonaws.com
            Action:
              - sts:AssumeRole

# roles ==================================================================================================================================

# layers ==================================================================================================================================
  commonLayer:
    Type: AWS::Serverless::LayerVersion
    Properties:
      LayerName: common_layer
      Description: Common layer for all functions
      ContentUri: src/layers/common_layer
      CompatibleRuntimes:
        - nodejs18.x
      RetentionPolicy: Delete 

  node14layer:
    Type: AWS::Serverless::LayerVersion
    Properties:
      LayerName: common_layer
      Description: Common layer for all functions
      ContentUri: src/layers/node14layer
      CompatibleRuntimes:
        - nodejs14.x
      RetentionPolicy: Delete 
# layers ==================================================================================================================================

  testFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: src/handlers/testFunction/
      Role: !GetAtt lambdaExecutionRole.Arn    
      Events:
        testFunction:
          Type: Api
          Properties:
            Path: /testFunction
            Method: GET

  node14funtion:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: src/handlers/node14function/
      Role: !GetAtt lambdaExecutionRole.Arn 
      Runtime: nodejs14.x   
      Events:
        testFunction:
          Type: Api
          Properties:
            Path: /testFunction
            Method: GET
